//===========
//Copyright 2022 Broadcom.  The term "Broadcom" refers solely to the 
//Broadcom Inc. corporate affiliate that distributes this software.
//===========
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_email_service_jni_ZosEmail */

#ifndef _Included_com_example_email_service_jni_ZosEmail
#define _Included_com_example_email_service_jni_ZosEmail
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_email_service_jni_ZosEmail
 * Method:    emailserv
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_email_service_jni_ZosEmail_emailserv
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
