CIUU020I '&PACKAGE CREATED'                              .ALARM=NO
'** Package &PACKAGE has been created***  '
CIUU021I 'CAST &PACKAGE '                              .ALARM=NO
'** &PACKAGE will be CAST by submitted batch job***  '
CIUU024E 'PACKAGE RESET IS RESTRICTED'                 .ALARM=NO
'** An APPROVED Package cannot be RESET ***  '
CIUU025I '*Select Elems for Packageing'          .ALARM=YES
'**Use this screen to select elements for Package processing**'
CIUU026E 'Incorrect Date field'                        .ALARM=NO
'** A date field is in an incorrect format***  '
CIUU027E 'Incorrect Prod Date '                        .ALARM=NO
'** Production date field is in an incorrect format***  '
CIUU029E 'Must use PACKAGE Tool'                       .ALARM=NO
'** You must use the PACKAGE tool to create new packages **  '
