name: Check Markdown links

on: pull_request

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: lycheeverse/lychee-action@v2
      with:
        fail: true
        failIfEmpty: true
