name: Submit Gradle Dependency Graph

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project-dir:
          - './output-management/web-viewer/favorites'
          - './output-management/web-viewer/favorites/favorites'
          - './output-management/web-viewer/downloader'
          - './output-management/web-viewer/downloader/application'
          - './output-management/web-viewer/api-basics/java'
          - './share/2022_columbus/AtoZ/email-spring-boot'
          
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Submit Dependency Graph for ${{ matrix.project-dir }}
        uses: gradle/actions/dependency-submission@v3
        with:
          gradle-version: '7.6.6'
          build-root-directory: ${{ matrix.project-dir }}
